expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    ports:
      http:
        nodePort: 30002  # 固定端口

# externalURL: http://192.168.31.69:30002  # 改成实际 IP

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: local-path
      size: 5Gi
    chartmuseum:
      storageClass: local-path
      size: 2Gi
    jobservice:
      storageClass: local-path
      size: 1Gi
    database:
      storageClass: local-path
      size: 1Gi
    redis:
      storageClass: local-path
      size: 1Gi
    trivy:
      storageClass: local-path
      size: 2Gi

harborAdminPassword: Harbor12345

metrics:
  enabled: true

trivy:
  enabled: true
