jenkins:
  persistence:
    enabled: false

  controller:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostName: "jenkins.local"
    installPlugins: []

    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  agent:
    enabled: false
