jenkins:
  persistence:
    enabled: false

  controller:
    service:
      type: ClusterIP
    installPlugins: []

    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: jenkins.local
        paths:
          - path: /
            pathType: Prefix

  agent:
    enabled: false
