apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io  # 改用官方仓库
    chart: harbor                       # Chart 名称
    targetRevision: 1.12.x              # 指定版本
    helm:
      valueFiles:
      - values.yaml                    # 引用 Git 中的 values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
