ingress-nginx:
  controller:
    image:
      repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/ingress-nginx/controller
      tag: v1.15.1
      digest: ""
    admissionWebhooks:
      patch:
        image:
          repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/ingress-nginx/kube-webhook-certgen
          tag: v1.6.9
          digest: ""
    service:
      type: NodePort
