ingress-nginx:
  controller:
    image:
      registry: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/ingress-nginx
      image: controller
      tag: v1.9.6
    admissionWebhooks:
      patch:
        image:
          registry: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/ingress-nginx
          image: kube-webhook-certgen
          tag: v1.6.9
    service:
      type: NodePort
