loki:
  deploymentMode: SingleBinary
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"

  schemaConfig:
    configs:
      - from: "2024-08-20"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi

  limits_config:
    retention_period: 168h

  promtail:
    enabled: true
    config:
      snippets:
        scrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_kubernetes_io_config_hash]
                action: drop
                regex: .*

  grafana:
    enabled: false
